### ISSUE TITLE
Getting a pool causes a pydantic error

### ISSUE THREAD

**Issue by Artem-Potapov** [PatriotRossii/e621-py#11]
Running this code
```
import e621

api = e621.E621(("JustMe_001", "n58BbxJAmp8SiwdRiwSQhcjQ"))
api.pools.get(21231)
```

Causes the pydantic error:
```
Traceback (most recent call last):
  File "C:\Users\potap\Desktop\pythonProjects\pythonProject4\main.py", line 4, in <module>
    api.pools.get(21231)
  File "C:\Users\potap\Desktop\pythonProjects\pythonProject4\e621-py-master\e621\endpoints.py", line 187, in wrapper
    return magical_method(*bound_signature.arguments.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potap\Desktop\pythonProjects\pythonProject4\e621-py-master\e621\endpoints.py", line 106, in _default_get
    return self._model.from_response(self._api.session.get(f"{self._url}/{identifier}", **kwargs), self._api)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potap\Desktop\pythonProjects\pythonProject4\e621-py-master\e621\base_model.py", line 55, in from_response
    return cls(**json, e621api=e621api)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Pool
is_deleted
  field required (type=value_error.missing)

Process finished with exit code 1
```

**Comment by Artem-Potapov** [comment]
I realised I'm a bit of an idiot and that the ```'is_deleted'``` field was replaced by some kind of other field or just deleted. I made a bogus quick fix for this in the ```base_model.py``` file:

This (line 54)
```
        elif isinstance(json, dict) and expect is dict:
            return cls(**json, e621api=e621api)
```
Became this
```
        elif isinstance(json, dict) and expect is dict:
            '''By artem: since api no longer has the property, just manually add it
            Please note that this realisation is bogus, and the method should be updated for new structure
            of the response JSON.
            '''
            if not ('is_deleted' in list(json.keys())):
                json['is_deleted'] = 'false'
            return cls(**json, e621api=e621api)
```

**Comment by Artem-Potapov** [comment]
Ok, I figured it out (how to fix the issue properly) and also found some other issues
in the models.py file change the class AuthenticatedUser to:
```
class AuthenticatedUser(User):
    wiki_page_version_count: int
    artist_version_count: int
    pool_version_count: int
    forum_post_count: int
    comment_count: int
    flag_count: int
    positive_feedback_count: int
    neutral_feedback_count: int
    negative_feedback_count: int
    upload_limit: int
    # show_avatars: bool (deprecated property)
    # blacklist_avatars: bool (deprecated property)
    blacklist_users: bool
    description_collapsed_initially: bool
    hide_comments: bool
    show_hidden_comments: bool
    show_post_statistics: bool
    has_mail: bool
    receive_email_notifications: bool
    enable_keyboard_navigation: bool
    enable_privacy_mode: bool
    style_usernames: bool
    enable_auto_complete: bool
    # has_saved_searches: bool
    disable_cropped_thumbnails: bool
    # disable_mobile_gestures: bool (deprecated property)
    enable_safe_mode: bool
    disable_responsive_mode: bool
    # disable_post_tooltips: bool (deprecated property)
    no_flagging: bool
    # no_feedback: bool (deprecated property)
    disable_user_dmails: bool
    enable_compact_uploader: bool
    replacements_beta: bool
    updated_at: str
    email: str
    last_logged_in_at: str
    last_forum_read_at: str
    recent_tags: str
    comment_threshold: int
    default_image_size: str
    favorite_tags: str
    blacklisted_tags: str
    time_zone: str
    per_page: int
    custom_style: str
    favorite_count: int
    api_regen_multiplier: int
    api_burst_limit: int
    remaining_api_limit: int
    statement_timeout: int
    favorite_limit: int
    tag_query_limit: int
```
(you can remove the commented ones, I left them so you could see what changed)
and in autogenerated_models.py change class Pool:
```
class Pool(BaseModel):
    id: int
    name: str
    created_at: str
    updated_at: Optional[str]
    creator_id: int
    description: str
    is_active: bool
    category: str
    # is_deleted: bool (deprecated property)
    post_ids: List[int]
    creator_name: str
    post_count: int
```

**Comment by Rriik** [comment]
To add to this, I have found another few fields that have since become obsolete. In `models.py`, comment out the following:

```
class Field720p(BaseModel):
    # type: str (deprecated property)
    height: int
    width: int
    # urls: List[Optional[str]] (deprecated property)
```

```
class Original(BaseModel):
    # type: str (deprecated property)
    height: int
    width: int
    # urls: List[Optional[str]] (deprecated property)
```

For me it kept breaking when pulling videos, probably due to recent changes they made to allow mp4 videos as well, who knows.
