### ISSUE TITLE
Certain Posts Cause Pydantic Errors

### ISSUE THREAD

**Issue by Ben-Brady** [PatriotRossii/e621-py#8]
## Description

Running the following code will cause a pydantic validation error due to the alternatives:
```py
from e621.api import E621
api = E621()
posts = api.posts.search(tags=["id:536580"])
```
Stacktrace:
```
Traceback (most recent call last):
  File "/home/ben/Documents/api/test.py", line 3, in <module>
    posts = api.posts.search(tags=["id:536580"])
  File "/home/ben/Documents/api/venv/lib/python3.10/site-packages/e621/endpoints.py", line 222, in search
    posts = self._default_search({"tags": tags}, limit, page, ignore_pagination)
  File "/home/ben/Documents/api/venv/lib/python3.10/site-packages/e621/endpoints.py", line 121, in _default_search
    return self._model.from_response(self._api.session.get(self._url, params=params), self._api, expect=list)
  File "/home/ben/Documents/api/venv/lib/python3.10/site-packages/e621/base_model.py", line 53, in from_response
    return cls.from_list(json, e621api)
  File "/home/ben/Documents/api/venv/lib/python3.10/site-packages/e621/base_model.py", line 23, in from_list
    return [cls(**obj, e621api=api) for obj in list]
  File "/home/ben/Documents/api/venv/lib/python3.10/site-packages/e621/base_model.py", line 23, in <listcomp>
    return [cls(**obj, e621api=api) for obj in list]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Post
sample -> alternates -> 720p -> urls -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
sample -> alternates -> 720p -> urls -> 1
  none is not an allowed value (type=type_error.none.not_allowed)
sample -> alternates -> 480p -> urls -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
sample -> alternates -> 480p -> urls -> 1
  none is not an allowed value (type=type_error.none.not_allowed)
```

## Specs
  OS: Ubuntu 20.04
  e621: 0.0.6
  python: 3.10.4

**Comment by eoan-ermine** [comment]
Thanks for your issue! It'll be resolved soon
